# Generated by Django 2.0.13 on 2019-04-05 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='学院编号')),
                ('name', models.CharField(max_length=30, verbose_name='学院名称')),
            ],
            options={
                'verbose_name': '学院表',
                'verbose_name_plural': '学院表',
                'db_table': 'colleges',
            },
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='专业编号')),
                ('name', models.CharField(max_length=30, verbose_name='专业名称')),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.College', verbose_name='学院')),
            ],
            options={
                'verbose_name': '专业表',
                'verbose_name_plural': '专业表',
                'db_table': 'specialtys',
            },
        ),
        migrations.CreateModel(
            name='SpecialtyTeacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.Specialty', verbose_name='专业')),
            ],
            options={
                'verbose_name': '专业教师表',
                'verbose_name_plural': '专业教师表',
                'db_table': 'specialty_teacher',
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('number', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='学号')),
                ('name', models.CharField(max_length=30, verbose_name='姓名')),
                ('password', models.CharField(max_length=200, verbose_name='密码')),
                ('identity', models.CharField(default='student', editable=False, max_length=20, verbose_name='身份')),
                ('total_time', models.CharField(default=0, editable=False, max_length=20, verbose_name='观看视频总时长')),
                ('profile_photo', models.ImageField(default='images/user_profile/default/default_student.png', editable=False, upload_to='images/user_profile/')),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.College', verbose_name='学院')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.Specialty', verbose_name='专业')),
            ],
            options={
                'verbose_name': '学生表',
                'verbose_name_plural': '学生表',
                'db_table': 'student_profile',
            },
        ),
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('number', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='学号')),
                ('name', models.CharField(max_length=30, verbose_name='姓名')),
                ('password', models.CharField(max_length=200, verbose_name='密码')),
                ('identity', models.CharField(default='teacher', editable=False, max_length=20, verbose_name='身份')),
                ('profile_photo', models.ImageField(default='images/user_profile/default/default_teacher.png', editable=False, upload_to='images/user_profile/')),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.College', verbose_name='学院')),
                ('specialty', models.ManyToManyField(through='userapp.SpecialtyTeacher', to='userapp.Specialty')),
            ],
            options={
                'verbose_name': '教师表',
                'verbose_name_plural': '教师表',
                'db_table': 'teacher_profile',
            },
        ),
        migrations.AddField(
            model_name='specialtyteacher',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.TeacherProfile', verbose_name='教师'),
        ),
    ]
